/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import type { OrderItemResponseDto } from './orderItemResponseDto';

export interface OrderResponseDto {
  orderId?: number;
  orderDate?: string;
  totalCost?: number;
  /** @nullable */
  items?: OrderItemResponseDto[] | null;
}
