/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */

export interface OrderItemResponseDto {
  beanId?: number;
  /** @nullable */
  beanName?: string | null;
  /** @nullable */
  image?: string | null;
  quantity?: number;
  unitPrice?: number;
}
