/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import type { CreateOrderItemDto } from './createOrderItemDto';

export interface UpdateOrderDto {
  /** @minItems 1 */
  items: CreateOrderItemDto[];
}
