/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  CoffeeBean,
  CoffeeBeanPagedResultDto,
  GetAllBeansParams
} from '../../models';

import { customAxiosInstance } from '../../../api/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getAllBeans = (
    params?: MaybeRef<GetAllBeansParams>,
 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customAxiosInstance<CoffeeBeanPagedResultDto>(
      {url: `/api/beans`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getGetAllBeansQueryKey = (params?: MaybeRef<GetAllBeansParams>,) => {
    return [
    'api','beans', ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllBeansQueryOptions = <TData = Awaited<ReturnType<typeof getAllBeans>>, TError = unknown>(params?: MaybeRef<GetAllBeansParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBeans>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetAllBeansQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBeans>>> = ({ signal }) => getAllBeans(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBeans>>, TError, TData> 
}

export type GetAllBeansQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBeans>>>
export type GetAllBeansQueryError = unknown



export function useGetAllBeans<TData = Awaited<ReturnType<typeof getAllBeans>>, TError = unknown>(
 params?: MaybeRef<GetAllBeansParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBeans>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllBeansQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const getBeanById = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customAxiosInstance<CoffeeBean>(
      {url: `/api/beans/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBeanByIdQueryKey = (id: MaybeRef<number>,) => {
    return [
    'api','beans',id
    ] as const;
    }

    
export const getGetBeanByIdQueryOptions = <TData = Awaited<ReturnType<typeof getBeanById>>, TError = unknown>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBeanById>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetBeanByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBeanById>>> = ({ signal }) => getBeanById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBeanById>>, TError, TData> 
}

export type GetBeanByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getBeanById>>>
export type GetBeanByIdQueryError = unknown



export function useGetBeanById<TData = Awaited<ReturnType<typeof getBeanById>>, TError = unknown>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBeanById>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBeanByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const getBeanOfTheDay = (
    
 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<CoffeeBean>(
      {url: `/api/beans/botd`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBeanOfTheDayQueryKey = () => {
    return [
    'api','beans','botd'
    ] as const;
    }

    
export const getGetBeanOfTheDayQueryOptions = <TData = Awaited<ReturnType<typeof getBeanOfTheDay>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBeanOfTheDay>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetBeanOfTheDayQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBeanOfTheDay>>> = ({ signal }) => getBeanOfTheDay(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBeanOfTheDay>>, TError, TData> 
}

export type GetBeanOfTheDayQueryResult = NonNullable<Awaited<ReturnType<typeof getBeanOfTheDay>>>
export type GetBeanOfTheDayQueryError = unknown



export function useGetBeanOfTheDay<TData = Awaited<ReturnType<typeof getBeanOfTheDay>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBeanOfTheDay>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBeanOfTheDayQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




