/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CoffeeBean,
  CoffeeBeanPagedResultDto
} from '../../models';


export const getGetAllBeansResponseMock = (overrideResponse: Partial<Extract<CoffeeBeanPagedResultDto, object>> = {}): CoffeeBeanPagedResultDto => ({items: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), image: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), colour: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), cost: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined])})), undefined]), totalCount: faker.helpers.arrayElement([faker.number.int(), undefined]), pageNumber: faker.helpers.arrayElement([faker.number.int(), undefined]), pageSize: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

export const getGetBeanByIdResponseMock = (overrideResponse: Partial<Extract<CoffeeBean, object>> = {}): CoffeeBean => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), image: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), colour: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), cost: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), ...overrideResponse})

export const getGetBeanOfTheDayResponseMock = (overrideResponse: Partial<Extract<CoffeeBean, object>> = {}): CoffeeBean => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), image: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), colour: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), cost: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), ...overrideResponse})


export const getGetAllBeansMockHandler = (overrideResponse?: CoffeeBeanPagedResultDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CoffeeBeanPagedResultDto> | CoffeeBeanPagedResultDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/beans', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllBeansResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetBeanByIdMockHandler = (overrideResponse?: CoffeeBean | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CoffeeBean> | CoffeeBean), options?: RequestHandlerOptions) => {
  return http.get('*/api/beans/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetBeanByIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetBeanOfTheDayMockHandler = (overrideResponse?: CoffeeBean | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CoffeeBean> | CoffeeBean), options?: RequestHandlerOptions) => {
  return http.get('*/api/beans/botd', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetBeanOfTheDayResponseMock(),
      { status: 200
      })
  }, options)
}
export const getBeansMock = () => [
  getGetAllBeansMockHandler(),
  getGetBeanByIdMockHandler(),
  getGetBeanOfTheDayMockHandler()
]
