/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateOrderDto,
  OrderResponseDto,
  UpdateOrderDto
} from '../../models';




  export const getOrders = () => {
const getApiOrders = <TData = AxiosResponse<OrderResponseDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders`,options
    );
  }
const postApiOrders = <TData = AxiosResponse<void>>(
    createOrderDto: CreateOrderDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/orders`,
      createOrderDto,options
    );
  }
const putApiOrdersId = <TData = AxiosResponse<void>>(
    id: number,
    updateOrderDto: UpdateOrderDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/orders/${id}`,
      updateOrderDto,options
    );
  }
const deleteApiOrdersId = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/orders/${id}`,options
    );
  }
return {getApiOrders,postApiOrders,putApiOrdersId,deleteApiOrdersId}};
export type GetApiOrdersResult = AxiosResponse<OrderResponseDto[]>
export type PostApiOrdersResult = AxiosResponse<void>
export type PutApiOrdersIdResult = AxiosResponse<void>
export type DeleteApiOrdersIdResult = AxiosResponse<void>
