/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateOrderDto,
  OrderResponseDto,
  UpdateOrderDto
} from '../../models';




  export const getOrders = () => {
const getMyOrders = <TData = AxiosResponse<OrderResponseDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders`,options
    );
  }
const createOrder = <TData = AxiosResponse<void>>(
    createOrderDto: CreateOrderDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/orders`,
      createOrderDto,options
    );
  }
const updateOrder = <TData = AxiosResponse<void>>(
    id: number,
    updateOrderDto: UpdateOrderDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/orders/${id}`,
      updateOrderDto,options
    );
  }
const cancelOrder = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/orders/${id}`,options
    );
  }
return {getMyOrders,createOrder,updateOrder,cancelOrder}};
export type GetMyOrdersResult = AxiosResponse<OrderResponseDto[]>
export type CreateOrderResult = AxiosResponse<void>
export type UpdateOrderResult = AxiosResponse<void>
export type CancelOrderResult = AxiosResponse<void>
