/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';
import type { OrderResponseDto } from '../../models';


export const getGetApiOrdersResponseMock = (): OrderResponseDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({ orderId: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), orderDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), totalCost: faker.helpers.arrayElement([faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }), undefined]), items: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({ beanId: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), beanName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), image: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), quantity: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), unitPrice: faker.helpers.arrayElement([faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }), undefined]) })), undefined]) })));


export const getGetApiOrdersMockHandler = (overrideResponse?: OrderResponseDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OrderResponseDto[]> | OrderResponseDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/orders', async (info) => {
    await delay(1000);

    return new HttpResponse(overrideResponse !== undefined
      ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
      : getGetApiOrdersResponseMock(),
      {
        status: 200,
        headers: { 'Content-Type': 'text/plain' }
      });
  }, options);
};

export const getPostApiOrdersMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/orders', async (info) => {
    await delay(1000);
    if (typeof overrideResponse === 'function') { await overrideResponse(info); }
    return new HttpResponse(null,
      {
        status: 200,

      });
  }, options);
};

export const getPutApiOrdersIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/orders/:id', async (info) => {
    await delay(1000);
    if (typeof overrideResponse === 'function') { await overrideResponse(info); }
    return new HttpResponse(null,
      {
        status: 200,

      });
  }, options);
};

export const getDeleteApiOrdersIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/orders/:id', async (info) => {
    await delay(1000);
    if (typeof overrideResponse === 'function') { await overrideResponse(info); }
    return new HttpResponse(null,
      {
        status: 200,

      });
  }, options);
};
export const getOrdersMock = () => [
  getGetApiOrdersMockHandler(),
  getPostApiOrdersMockHandler(),
  getPutApiOrdersIdMockHandler(),
  getDeleteApiOrdersIdMockHandler()];
