/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';

import type {
  GreetingMessage
} from '../../models';

import { customAxiosInstance } from '../../../api/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const greeting = (
    
 options?: SecondParameter<typeof customAxiosInstance>,signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<GreetingMessage>(
      {url: `/api/greeting`, method: 'GET', signal
    },
      options);
    }
  



export const getGreetingQueryKey = () => {
    return [
    'api','greeting'
    ] as const;
    }

    
export const getGreetingQueryOptions = <TData = Awaited<ReturnType<typeof greeting>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof greeting>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGreetingQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof greeting>>> = ({ signal }) => greeting(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof greeting>>, TError, TData> 
}

export type GreetingQueryResult = NonNullable<Awaited<ReturnType<typeof greeting>>>
export type GreetingQueryError = unknown



export function useGreeting<TData = Awaited<ReturnType<typeof greeting>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof greeting>>, TError, TData>>, request?: SecondParameter<typeof customAxiosInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGreetingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




