/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GreetingMessage
} from '../../models';


export const getGreetingResponseMock = (overrideResponse: Partial<Extract<GreetingMessage, object>> = {}): GreetingMessage => ({message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})


export const getGreetingMockHandler = (overrideResponse?: GreetingMessage | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GreetingMessage> | GreetingMessage), options?: RequestHandlerOptions) => {
  return http.get('*/api/greeting', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGreetingResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGreetingMock = () => [
  getGreetingMockHandler()
]
