/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthResponseDto,
  LoginDto,
  RegisterDto
} from '../../models';




  export const getAuth = () => {
const postApiAuthRegister = <TData = AxiosResponse<void>>(
    registerDto: RegisterDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/register`,
      registerDto,options
    );
  }
const postApiAuthLogin = <TData = AxiosResponse<AuthResponseDto>>(
    loginDto: LoginDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login`,
      loginDto,options
    );
  }
return {postApiAuthRegister,postApiAuthLogin}};
export type PostApiAuthRegisterResult = AxiosResponse<void>
export type PostApiAuthLoginResult = AxiosResponse<AuthResponseDto>
