/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AuthResponseDto
} from '../../models';


export const getLoginResponseMock = (overrideResponse: Partial< AuthResponseDto > = {}): AuthResponseDto => ({token: faker.string.alpha({length: {min: 1, max: 20}}), username: faker.string.alpha({length: {min: 1, max: 20}}), email: faker.string.alpha({length: {min: 1, max: 20}}), ...overrideResponse})


export const getRegisterMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/register', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getLoginMockHandler = (overrideResponse?: AuthResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AuthResponseDto> | AuthResponseDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/login', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAuthMock = () => [
  getRegisterMockHandler(),
  getLoginMockHandler()]
