/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import type { CoffeeBean } from './coffeeBean';

export interface CoffeeBeanPagedResultDto {
  /** @nullable */
  items?: CoffeeBean[] | null;
  totalCount?: number;
  pageNumber?: number;
  pageSize?: number;
}
