/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */

export interface CreateOrderItemDto {
  beanId: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  quantity: number;
}
