/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */

export interface OrderItemResponseDto {
  beanId?: number;
  /** @nullable */
  beanName?: string | null;
  /** @nullable */
  image?: string | null;
  quantity?: number;
  unitPrice?: number;
}
