/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import type { CreateOrderItemDto } from './createOrderItemDto';

export interface UpdateOrderDto {
  /** @minItems 1 */
  items: CreateOrderItemDto[];
}
