/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */

export interface AuthResponseDto {
  /** @nullable */
  token?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  email?: string | null;
}
