/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */

export type GetAllBeansParams = {
Search?: string;
Page?: number;
PageSize?: number;
};
