/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */

export type GetAllBeansParams = {
search?: string;
page?: number;
pageSize?: number;
};
