/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  password: string;
}
