/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import type {
  CoffeeBean,
  CoffeeBeanPagedResultDto,
  GetAllBeansParams
} from '../../models';

import { customInstance } from '../../../api/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getBeans = () => {
const getAllBeans = (
    params?: GetAllBeansParams,
 options?: SecondParameter<typeof customInstance<CoffeeBeanPagedResultDto>>,) => {
      return customInstance<CoffeeBeanPagedResultDto>(
      {url: `/api/beans`, method: 'GET',
        params
    },
      options);
    }
  const getBeanById = (
    id: number,
 options?: SecondParameter<typeof customInstance<CoffeeBean>>,) => {
      return customInstance<CoffeeBean>(
      {url: `/api/beans/${id}`, method: 'GET'
    },
      options);
    }
  const getBeanOfTheDay = (
    
 options?: SecondParameter<typeof customInstance<CoffeeBean>>,) => {
      return customInstance<CoffeeBean>(
      {url: `/api/beans/botd`, method: 'GET'
    },
      options);
    }
  return {getAllBeans,getBeanById,getBeanOfTheDay}};
export type GetAllBeansResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBeans>['getAllBeans']>>>
export type GetBeanByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBeans>['getBeanById']>>>
export type GetBeanOfTheDayResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBeans>['getBeanOfTheDay']>>>
