/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';
import type { CoffeeBean, CoffeeBeanPagedResultDto } from '../../models';


export const getGetApiBeansResponseMock = (overrideResponse: Partial<CoffeeBeanPagedResultDto> = {}): CoffeeBeanPagedResultDto => ({ items: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({ id: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), image: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), colour: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), cost: faker.helpers.arrayElement([faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }), undefined]) })), undefined]), totalCount: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), pageNumber: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), pageSize: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), ...overrideResponse });

export const getGetApiBeansIdResponseMock = (overrideResponse: Partial<CoffeeBean> = {}): CoffeeBean => ({ id: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), image: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), colour: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), cost: faker.helpers.arrayElement([faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }), undefined]), ...overrideResponse });

export const getGetApiBeansBotdResponseMock = (overrideResponse: Partial<CoffeeBean> = {}): CoffeeBean => ({ id: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]), name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), image: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), colour: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]), cost: faker.helpers.arrayElement([faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }), undefined]), ...overrideResponse });


export const getGetApiBeansMockHandler = (overrideResponse?: CoffeeBeanPagedResultDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CoffeeBeanPagedResultDto> | CoffeeBeanPagedResultDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/beans', async (info) => {
    await delay(1000);

    return new HttpResponse(overrideResponse !== undefined
      ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
      : getGetApiBeansResponseMock(),
      {
        status: 200,
        headers: { 'Content-Type': 'text/plain' }
      });
  }, options);
};

export const getGetApiBeansIdMockHandler = (overrideResponse?: CoffeeBean | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CoffeeBean> | CoffeeBean), options?: RequestHandlerOptions) => {
  return http.get('*/api/beans/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(overrideResponse !== undefined
      ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
      : getGetApiBeansIdResponseMock(),
      {
        status: 200,
        headers: { 'Content-Type': 'text/plain' }
      });
  }, options);
};

export const getGetApiBeansBotdMockHandler = (overrideResponse?: CoffeeBean | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CoffeeBean> | CoffeeBean), options?: RequestHandlerOptions) => {
  return http.get('*/api/beans/botd', async (info) => {
    await delay(1000);

    return new HttpResponse(overrideResponse !== undefined
      ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
      : getGetApiBeansBotdResponseMock(),
      {
        status: 200,
        headers: { 'Content-Type': 'text/plain' }
      });
  }, options);
};
export const getBeansMock = () => [
  getGetApiBeansMockHandler(),
  getGetApiBeansIdMockHandler(),
  getGetApiBeansBotdMockHandler()];
