/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CoffeeBean,
  CoffeeBeanPagedResultDto,
  GetAllBeansParams
} from '../../models';




export const getBeans = () => {
  const getAllBeans = <TData = AxiosResponse<CoffeeBeanPagedResultDto>>(
    params?: GetAllBeansParams, options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(
      `/api/beans`, {
      ...options,
      params: { ...params, ...options?.params },
    }
    );
  };
  const getBeanById = <TData = AxiosResponse<CoffeeBean>>(
    id: number, options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(
      `/api/beans/${id}`, options
    );
  };
  const getBeanOfTheDay = <TData = AxiosResponse<CoffeeBean>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(
      `/api/beans/botd`, options
    );
  };
  return { getAllBeans, getBeanById, getBeanOfTheDay };
};
export type GetAllBeansResult = AxiosResponse<CoffeeBeanPagedResultDto>;
export type GetBeanByIdResult = AxiosResponse<CoffeeBean>;
export type GetBeanOfTheDayResult = AxiosResponse<CoffeeBean>;
