/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CoffeeBean,
  CoffeeBeanPagedResultDto,
  GetApiBeansParams
} from '../../models';




  export const getBeans = () => {
const getApiBeans = <TData = AxiosResponse<CoffeeBeanPagedResultDto>>(
    params?: GetApiBeansParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/beans`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getApiBeansId = <TData = AxiosResponse<CoffeeBean>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/beans/${id}`,options
    );
  }
const getApiBeansBotd = <TData = AxiosResponse<CoffeeBean>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/beans/botd`,options
    );
  }
return {getApiBeans,getApiBeansId,getApiBeansBotd}};
export type GetApiBeansResult = AxiosResponse<CoffeeBeanPagedResultDto>
export type GetApiBeansIdResult = AxiosResponse<CoffeeBean>
export type GetApiBeansBotdResult = AxiosResponse<CoffeeBean>
