/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AllTheBeans.API
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  OrderResponseDto
} from '../../models';


export const getGetMyOrdersResponseMock = (): OrderResponseDto[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({orderId: faker.helpers.arrayElement([faker.number.int(), undefined]), orderDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), totalCost: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), items: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({beanId: faker.helpers.arrayElement([faker.number.int(), undefined]), beanName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), image: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), quantity: faker.helpers.arrayElement([faker.number.int(), undefined]), unitPrice: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined])})), undefined])})))


export const getGetMyOrdersMockHandler = (overrideResponse?: OrderResponseDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OrderResponseDto[]> | OrderResponseDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/orders', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMyOrdersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateOrderMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/orders', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getUpdateOrderMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/orders/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getCancelOrderMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/orders/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getOrdersMock = () => [
  getGetMyOrdersMockHandler(),
  getCreateOrderMockHandler(),
  getUpdateOrderMockHandler(),
  getCancelOrderMockHandler()
]
